### ISSUE TITLE
error compiling on 1.13 / arm64

### ISSUE THREAD

**Issue by jamespo** [ameshkov/dnslookup#2]
james@orangepi3:~ $ go get github.com/ameshkov/dnslookup
    go/src/github.com/ameshkov/dnslookup/main.go:76:27: cannot use &req (type *"github.com/miekg/dns".Msg) as type *"github.com/AdguardTeam/dnsproxy/vendor/github.com/miekg/dns".Msg in argument to u.Exchange
    james@orangepi3:~ $ go version
    go version go1.13.1 linux/arm64

**Comment by ameshkov** [comment]
What about this?
```
git clone https://github.com/ameshkov/dnslookup.git
cd dnslookup
make
```

**Comment by jamespo** [comment]
ah - works well. Thank you.
