### ISSUE TITLE
Not working? --> RRTYPE=PTR dnslookup 8.8.8.8 tls://1.1.1.1       

### ISSUE THREAD

**Issue by petrich** [ameshkov/dnslookup#22]
Hi there, great tool. 

But how to make a `PTR`  request... the following does not work:

`RRTYPE=PTR dnslookup 8.8.8.8 tls://1.1.1.1`

Should return `dns.google.`  

Any Idea?

**Comment by ameshkov** [comment]
`8.8.8.8` is not a valid domain name.

It should be `RRTYPE=PTR dnslookup 8.8.8.8.in-addr.arpa tls://1.1.1.1`

**Comment by petrich** [comment]
Ahh... Great... Thank you.
