### ISSUE TITLE
TCP option for Plain DNS ?

### ISSUE THREAD

**Issue by petrich** [ameshkov/dnslookup#23]
Hi There... is there any option to use `tcp` instead of `udp` for Plain DNS? 

ie. like this:
`TCP=1 dnslookup example.org 94.140.14.14`

Greetings

**Comment by ameshkov** [comment]
Hi, sure! Here it is: `dnslookup example.org tcp://94.140.14.14`

**Comment by petrich** [comment]
Ahh... great. Thank you very much.
