### ISSUE TITLE
v1.7.0 can't query NextDNS

### ISSUE THREAD

**Issue by timkgh** [ameshkov/dnslookup#27]
dnslookup google.com tls://dns.nextdns.io
dnslookup v. v1.7.0
2022/06/04 13:49:56 Cannot make the DNS request: getting connection to tls://dns.nextdns.io:853: connecting to dns.nextdns.io: x509: “dns.nextdns.io” certificate is not standards compliant

Not sure whether the problem is on the NextDNS side or dnslookup issue.

This is the dnslookup darwin build running on macOS 12.4

**Comment by ameshkov** [comment]
It seems to be a macOS-specific issue with Golang: https://github.com/golang/go/issues/51991

Some people in that thread claim that it goes away after the macOS update.
