### ISSUE TITLE
Can not use tls://94.140.14.14 in windows7

### ISSUE THREAD

**Issue by Lanius-collaris** [ameshkov/dnslookup#29]
`./dnslookup github.com tls://94.140.14.14`

error:
```
2022/07/31 15:14:34 Cannot make the DNS request: getting connection to tls://94.
140.14.14:853: connecting to 94.140.14.14: x509: certificate is valid for 94.140
.14.14, 94.140.14.140, 94.140.14.141, 94.140.14.15, 94.140.15.15, 94.140.15.16,
not 94.140.14.14
```

**Comment by ameshkov** [comment]
This is an old golang issue and I don't think they'll fix it since Windows 7 is not supported anymore

**Comment by sergeevabc** [comment]
Андрей, вы с языком Go на ты, ваши решения используют в разных проектах, авось вы и могли бы сделать патч, исправляющий этот косяк сетевой библиотеки. Ведь все без исключения программы на Go, использующие её, не могут соединиться с DoH по айпишнику. А, например, Dig, как и популярные браузеры, написанные на C++, прекрасно соединяются под Windows 7.

``` console
$ dnslookup cern.ch https://1.1.1.1/dns-query
[fatal] Cannot make the DNS request: requesting https://1.1.1.1:443/dns-query: Get "https://1.1.1.1:443/dns-query?dns=AAABAAABAAAAAAAABGNlcm4CY2gAAAEAAQ": tls: failed to verify certificate: x509: certificate is valid for 1.0.0.1, 1.1.1.1, 162.159.36.1, 162.159.46.1, 2606:4700:4700::1001, 2606:4700:4700::1111, 2606:4700:4700::64, 2606:4700:4700::6400, not 1.1.1.1

$ dig cern.ch +short +https @1.1.1.1
194.190.168.1
```

**Comment by ameshkov** [comment]
Он давно исправлен в новых версиях Go, которые с Win7 не работают. Я к сожалению не могу это исправить ВНЕ Go просто в самой программе.

**Comment by sergeevabc** [comment]
Андрей, либо мы говорим о разных косяках, либо я не знаю, что и думать. Есть же свежий Go, который работает под Windows 7. С его помощью я компилирую любую Go-программу с сетевым компонентом, пытаюсь соединиться с DoH/DoT-сервером и получаю ошибку.

``` console
$ ver & go version
Microsoft Windows [Version 6.1.7601]
go version go1.24.4 windows/amd64

$ git clone https://github.com/ameshkov/dnslookup && cd dnslookup

$ go build
go: downloading github.com/AdguardTeam/dnsproxy v0.71.1
go: downloading github.com/AdguardTeam/golibs v0.23.2
go: downloading github.com/ameshkov/dnsstamps v1.0.3
go: downloading github.com/miekg/dns v1.1.59
go: downloading github.com/ameshkov/dnscrypt/v2 v2.3.0
go: downloading github.com/quic-go/quic-go v0.43.1
go: downloading golang.org/x/crypto v0.23.0
go: downloading github.com/quic-go/qpack v0.4.0
go: downloading golang.org/x/exp v0.0.0-20240506185415-9bf2ced13842
go: downloading golang.org/x/text v0.15.0
go: downloading github.com/aead/chacha20 v0.0.0-20180709150244-8b13a72661da
go: downloading github.com/aead/poly1305 v0.0.0-20180717145839-3fee0db0b635

$ dnslookup cern.ch https://1.1.1.1/dns-query
dnslookup master
2025/06/09 14:58:05 [fatal] Cannot make the DNS request: requesting https://1.1.1.1:443/dns-query: Get "https://1.1.1.1:443/dns-query?dns=AAABAAABAAAAAAAABGNlcm4CY2gAAAEAAQ": tls: failed to verify certificate: x509: certificate is valid for 1.0.0.1, 1.1.1.1, 162.159.36.1, 162.159.46.1, 2606:4700:4700::1001, 2606:4700:4700::1111, 2606:4700:4700::64, 2606:4700:4700::6400, not 1.1.1.1

$ dnslookup cern.ch https://one.one.one.one/dns-query
dnslookup master
Server: https://one.one.one.one/dns-query

dnslookup result (elapsed 238.0006ms):
;; opcode: QUERY, status: NOERROR, id: 24474
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;cern.ch.       IN       A

;; ANSWER SECTION:
cern.ch.        245     IN      A       188.184.77.250
```

**Comment by ameshkov** [comment]
Все, сейчас врубился.

* Go на Windows отдает проверку сертификатов на откуп системным API (Crypt32)
* При этом в работе на Win7 есть баги, которые исправлять никто конечно не будет, так как Win7 уже сняли с поддержки.

Что можно попробовать если очень нужен именно IP-адрес в домене:

1. `dnslookup` вызывать с VERIFY=0 (но это не со всеми Go-программами поможет)
2. Попробовать полностью отключить сетевой IPv6 интерфейс в Windows. Есть вероятность, что из-за наличия этого интерфейса IP-адрес представлен в IPv6-форме и `::ffff:94.140.14.14`

**Comment by sergeevabc** [comment]
Андрей, ранее я уже писал, что существуют программы на других языках программирования, которые без проблем подключаются к DoH по голому айпишнику под Windows 7.

Например, на С++ написаны утилита dig…

``` console
$ ver & dig.exe -v
Microsoft Windows [Version 6.1.7601]
DiG 9.17.15

$ dig cern.ch +short +https @1.1.1.1
188.184.77.250
```

…и популярные браузеры вроде Chrome (109) и Firefox (135).

![](https://github.com/user-attachments/assets/5117fff6-7833-4214-9d03-04a70893754a)

![](https://github.com/user-attachments/assets/cd253e1d-6e90-4c07-9703-91b000d76845)

![](https://github.com/user-attachments/assets/75e23508-b408-415d-914f-cc2396052836)

Или вот есть [dnspython](https://github.com/rthalley/dnspython) на языке Python.

``` console
$ ver & python --version
Microsoft Windows [Version 6.1.7601]
Python 3.13.2

$ cat doh.py
import httpx
import dns.message
import dns.query
import dns.rdatatype
def main():
    where = "https://1.1.1.1/dns-query"
    qname = "cern.ch"
    with httpx.Client() as client:
        q = dns.message.make_query(qname, dns.rdatatype.A)
        r = dns.query.https(q, where, session=client)
        for answer in r.answer:
            print(answer)
if __name__ == "__main__":
    main()

$ python doh.py
cern.ch. 436 IN A 188.184.77.250
```

Корректная работа упомянутых программ под Windows 7 убеждает меня в том, что языку Go либо недостаёт функциональности подключения к DoH/DoT-серверам по айпишнику, либо она реализована с ошибкой. Значит, это можно исправить именно в рамках сетевой библиотеки Go, не ссылаясь на API Windows.
