### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by geraldvillorente** [ameshkov/dnslookup#3]
Here is the full output.

```
$ go get github.com/ameshkov/dnslookup
# github.com/ameshkov/dnslookup
go/src/github.com/ameshkov/dnslookup/main.go:80:27: cannot use &req (type *"github.com/miekg/dns".Msg) as type *"github.com/AdguardTeam/dnsproxy/vendor/github.com/miekg/dns".Msg in argument to u.Exchange
```

**Comment by ameshkov** [comment]
Well, it seems it's not compatible with this kind of installation.

If you want to build it from sources, clone the repo and run `go build -mod vender` or `VERSION=1.3.0 make`.

Otherwise, you can simply get one of the binaries from https://github.com/ameshkov/dnslookup/releases
