### ISSUE TITLE
Problem with IP-base DoH

### ISSUE THREAD

**Issue by alidxdydz** [ameshkov/dnslookup#54]
Hi,

I wonder why I can't use these types of DoH addresses:

https://8.8.8.8/dns_query
https://1.1.1.1/dns_query
https://77.88.8.8/dns_query

**Comment by ameshkov** [comment]
Hi, it should be `dns-query`, not `dns_query`

**Comment by alidxdydz** [comment]
@ameshkov 

Thank you for the correction but it doesn't work.

**Comment by ameshkov** [comment]
Works on my side
![image](https://github.com/ameshkov/dnslookup/assets/5947035/511d1ee9-fcf4-44bb-ac5c-4849b77359cb)

**Comment by alidxdydz** [comment]
@ameshkov 

I'm sorry for my response but it doesn't work on my side on Windows OS.

![IMG_20230706_171027_130.jpg](https://github.com/ameshkov/dnslookup/assets/132169513/d928f81e-f0f9-4df0-bf40-3330ac400cb9)

**Comment by alidxdydz** [comment]
@ameshkov 

I'm sorry for my late response but it doesn't work on my side on Windows OS.

![IMG_20230706_171027_130.jpg](https://github.com/ameshkov/dnslookup/assets/132169513/12ffc005-205a-4dc5-9ce0-88524384845f)

**Comment by ameshkov** [comment]
@alidxdydz got it, that's a known issue on Windows, the bug is in `crypto/tls` library of Golang so it cannot be fixed on our side.

The only thing that I'd suggest is to disable TLS verification: `VERIFY=0 dnslookup example.org https://1.1.1.1/dns-query`
