### ISSUE TITLE
Accept query type argument

### ISSUE THREAD

**Issue by hackel** [ameshkov/dnslookup#6]
It would be very useful to be able to supply the query type (A, AAAA, MX, etc.) when using this tool.  I don't know go, but a quick look at the dns library makes it look pretty easy to add.

**Comment by timkgh** [comment]
+1

**Comment by ameshkov** [comment]
Possible with `RRTYPE`: `RRTYPE=AAAA ./dnslookup example.org tls://dns.google`

**Comment by timkgh** [comment]
Possible, but not ergonomic at all to use, not in the help.

How can a user discover it and remember how to use it?

**Comment by huyz** [comment]
I also find it a bit strange that options are passed by environment variable rather than as arguments to the command. Not typical for CLI commanda

**Comment by ameshkov** [comment]
Yeah, the CLI interface is rather ugly at the moment indeed.

I just don't have enough spare time to rework it.

Also, after reworking the CLI interface, I'll likely have to call it version 2.0 since it won't be compatible with v1.

**Comment by ainar-g** [comment]
@ameshkov, it's exceptionally unergonomic in PowerShell.  Since there is currently no way to set an environment variable for one command only, one has to do something like this:

```ps1
powershell -Command { $Env:RRTYPE='MX'; dnslookup 'my-mail.example' '94.140.15.15' }
```

I'd suggest at least reopening the issue.

**Comment by ameshkov** [comment]
I'd prefer to completely change the command-line interface in /v2, it's not just about query type
