### ISSUE TITLE
Packaging request: Homebrew

### ISSUE THREAD

**Issue by huyz** [ameshkov/dnslookup#9]
Can this be submitted as a Homebrew formula (both macOS and Linuxbrew) so that we can easily get updates?

**Comment by ameshkov** [comment]
Well, if someone can a brew formulae for it, I'll be happy about it.

Brew does not like authors submitting their own work:

https://docs.brew.sh/Acceptable-Formulae

> We frown on authors submitting their own work unless it is very popular.

**Comment by ameshkov** [comment]
Well, actually there is a way now

```
brew install ameshkov/tap/dnslookup
```

**Comment by huyz** [comment]
Oh great, thanks!
